name: Deploy Svelte App to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger deployment on push to master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout master branch (source code)
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 1

      # Step 2: Install bun
      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bun install

      # Step 4: Build the Svelte app
      - name: Build the app
        run: bun run build

      # Step 5: Deploy to github-pg branch
      - name: Deploy to github-pg
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Replace with your actual output directory (e.g., dist or public)
          publish_branch: github-pg
          force_orphan: true    # Optional: ensures a clean commit history on github-pg
